# This workflow will do a clean install of repo dependencies and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NextJS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
    - run: yarn lint

    - name: Veracode Upload And Scan
  # You may pin to the exact commit or the version.
  # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
      uses: veracode/veracode-uploadandscan-action@0.2.1
      with:
    # appname
         appname:  'uiclaim.tracker'
    # createprofile
         createprofile: true
    # filepath
         filepath:  .
    # version
         version:  ${{ github.run_id }}
    # vid
         vid: ${{ secrets.id }}
    # vkey
         vkey:  ${{ secrets.key }}
